const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={};try{state=window.CLOUD_MODE?window.CLOUD_INITIAL_STATE:JSON.parse(localStorage.getItem('kyushu-2026')||'{}')||{};if(typeof state!=='object'||Array.isArray(state))state={};}catch{$('#status').textContent='無法讀取已儲存資料；你仍可使用旅行手冊。';}
function save(key){if(window.CLOUD_MODE){window.cloudSave(key,state[key]);return;}try{localStorage.setItem('kyushu-2026',JSON.stringify(state));$('#status').textContent='已儲存在此裝置';}catch{$('#status').textContent='目前無法儲存；勾選只會保留到本次瀏覽結束。';}}
const flightKey=d=>'flight-'+d.day+'-'+d.flight.revision;
const check=(id,label,cls='')=>`<label class="check ${cls}"><input type="checkbox" data-key="${id}" ${state[id]?'checked':''}><span>${label}</span></label>`;
const map=location=>`<a class="map" target="_blank" rel="noopener noreferrer" aria-label="在 Google Maps 搜尋 ${esc(location)}（另開視窗）" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}">MAP ↗</a>`;
const section=(en,zh)=>`<div class="section-heading"><h2>${en}</h2><span>${zh}</span></div>`;
const art=`<svg class="landscape" viewBox="0 0 520 190" fill="none" aria-hidden="true"><circle cx="393" cy="47" r="29" fill="#eec9b8"/><path d="M10 156L102 72L139 103L222 27L327 154M144 156L232 80L295 117L350 74L449 156" stroke="#8a9b98" stroke-width="2"/><path d="M189 61L222 27L256 69L230 59L213 68Z" fill="#e6ebe6"/><path d="M0 170Q120 149 234 171T520 165" stroke="#a7b6bc" stroke-width="2"/><path d="M363 138H427M372 138V158M418 138V158M369 132H421M379 130V123M411 130V123" stroke="#b95b49" stroke-width="3"/><path d="M55 167Q39 150 53 144M68 166Q52 148 66 141M81 165Q65 150 79 142" stroke="#b6a79b" stroke-width="2"/><path d="M457 47l27 -12 -14 19 -5 -8z" stroke="#81959f" stroke-width="1.5"/></svg>`;
function home(){return `<section class="hero"><div class="eyebrow">A LITTLE ADVENTURE, TOGETHER</div><h1>KYUSHU<span>九州親子旅行</span></h1><p class="date">2026.09.24 <i>—</i> 09.29</p><p class="smallcaps">6 DAYS / 5 NIGHTS</p>${art}<div class="trip-meta"><span>2 大 ＋ 1 小</span><span>自駕 × 城市散步</span><span>6 天的親子記憶</span></div></section><section>${section('OUR SIX DAYS','翻開每一天')}<div class="day-grid">${TRIP.days.map(d=>`<a class="day-card tone-${d.day}" href="#/day/${d.day}">${PHOTOS[photoDays[d.day-1][0]]?`<img class="card-photo" src="${PHOTOS[photoDays[d.day-1][0]].src}" alt="" loading="lazy">`:""}<div class="card-top"><span>DAY <b>0${d.day}</b></span><span>${d.date} ${d.weekday}</span></div><h3>${d.route.replace('機場','')}</h3><div class="card-bottom"><span>${d.subtitle}</span><span class="arrow">↗</span></div></a>`).join('')}</div></section><section>${section('DRIVING SUMMARY','交通總覽')}<div class="driving-intro"><span class="pill">09.24 — 09.27 自駕</span><p>Day 4 抵達福岡後還車<br><small>${TRIP.luggage}</small></p></div><div class="driving-list">${TRIP.days.map(d=>`<a href="#/day/${d.day}"><b>0${d.day}</b><span>${d.day>4?'NO CAR · 大眾運輸':d.route}</span><strong>${d.day>4?'0 km':d.driveTime}</strong></a>`).join('')}</div></section>${rentalSection()}${hotelSection()}<section>${section('BEFORE WE GO','出發前清單')}<div class="checklist">${TRIP.checklist.map((x,i)=>check('list-'+i,esc(x))).join('')}</div><p class="fine">${window.CLOUD_MODE?"登入同一 Google 帳號即可跨裝置同步。":"目前為本機模式，勾選僅保存在此瀏覽器。"}</p></section><div class="closing">旅途慢一點，回憶多一點。<span>KYUSHU FAMILY TRIP 2026</span></div>`;}
function dayPage(d){const done=d.timeline.filter(t=>state[t.id]).length;return `<section class="day-hero"><div class="eyebrow">${d.title}</div><div class="day-title"><h1>DAY <em>0${d.day}</em></h1><p>${d.date}<span>${d.weekday} / ${d.weekdayZh}</span></p></div><h2>${d.route}</h2><p class="subtitle">${d.subtitle}</p>${d.day>4?'<span class="pill blue">NO CAR DAY · 0 km</span>':''}</section><section>${section('TODAY SUMMARY','今日概覽')}<div class="summary"><div><span>今日開車</span><strong>${d.day<=4?'自駕'+(d.day===4?'・福岡還車':''):'0 km'}</strong></div><div><span>預估總車程／交通</span><strong>${d.driveTime}</strong></div><div><span>今日住宿</span><strong>${d.hotel}</strong></div><div><span>今日重點</span><strong>${d.highlights}</strong></div></div></section>${d.flight?`<section class="flight"><div><span class="tag">FLIGHT / 已提供航班</span><h2>${esc(d.flight.number)} · ${d.flight.label}</h2><p><strong>座位 ${esc(d.flight.seats)}</strong> · ${esc(d.flight.timezone)}</p><p><strong>起飛 ${esc(state[flightKey(d)]||d.flight.value)}（${esc(d.flight.timezone)}） → 抵達 ${esc(d.flight.arrival)}（${esc(d.flight.arrivalTimezone)}）</strong></p><p>${esc(d.flight.note)}</p><p>修改起飛時間不會自動推移其他行程。</p></div><label>航班時間<input aria-label="${d.flight.label}" type="time" data-flight="${d.day}" value="${esc(state[flightKey(d)]||d.flight.value)}"></label></section>`:''}<section class="alerts">${d.alerts.map(a=>`<aside><span class="tag">${/待確認|官方|停航/.test(a)?'待確認 / CHECK':'TRAVEL NOTE'}</span><p>${a}</p></aside>`).join('')}</section>${d.alternativePlan?`<details class="alternative"><summary><span>ALTERNATIVE PLAN <b>備用行程</b></span><span>＋</span></summary><div><h3>${d.alternativePlan.route}</h3><p>${d.alternativePlan.note}</p></div></details>`:''}${[1,4].includes(d.day)?rentalSection(d.day):""}${weatherSection(d)}${gallery(d)}${hotelSection(d)}<section>${section('TODAY TIMELINE','今日時間軸')}<div class="progress-line"><span id="count">已完成 ${done} / ${d.timeline.length}</span><progress id="progress" value="${done}" max="${d.timeline.length}" aria-label="今日行程完成度"></progress></div><div class="timeline">${d.timeline.map((t,i)=>`<article class="event ${state[t.id]?'complete':''}"><div class="event-time">${esc(d.flight&&t.flight?(state[flightKey(d)]||t.time):t.time)}</div><div class="event-body"><div class="event-heading">${check(t.id,esc(t.title),'event-check')}</div><div class="location"><span>${esc(t.location)}</span>${!t.location.includes('住宿')&&!t.location.includes('待確認')?map(t.location):''}</div><div class="transport"><span>${esc(t.transport)}</span>${t.duration!=='—'?`<span>◷ ${esc(t.duration)}</span>`:''}</div><p>${esc(t.note)}</p></div></article>`).join('')}</div></section>${nearbySection(d)}<section>${section('DAILY CHECK','隨手確認')}<div class="checklist">${['行李與隨身物品','今日住宿／返家確認',d.day<=4?'停車與行車安排':'大眾運輸路線'].map((x,i)=>check(`daycheck-${d.day}-${i}`,x)).join('')}</div></section>`;}
let current=0;
function render(focus=false){const match=location.hash.match(/^#\/day\/([1-6])$/);current=match?Number(match[1]):0;$('#day-nav').innerHTML=`<a href="#/" ${!current?'aria-current="page"':''}>首頁</a>`+TRIP.days.map(d=>`<a href="#/day/${d.day}" ${current===d.day?'aria-current="page"':''}>DAY ${d.day}</a>`).join('');$('#main').innerHTML=current?dayPage(TRIP.days[current-1]):home();$('#bottom').innerHTML=current?`${current>1?`<a href="#/day/${current-1}">← <span>Previous Day</span></a>`:'<span class="disabled">← Previous Day</span>'}<a href="#/">⌂ HOME</a>${current<6?`<a href="#/day/${current+1}"><span>Next Day</span> →</a>`:'<span class="disabled">Next Day →</span>'}`:'<span>2026 九州親子旅行</span><a href="#/day/1">開啟旅程 →</a>';enhancePage(current?TRIP.days[current-1]:null);document.title=(current?`Day ${current} · `:'')+TRIP.name;if(focus){window.scrollTo(0,0);$('#main').focus({preventScroll:true});}}
document.addEventListener('change',e=>{if(e.target.dataset.key){state[e.target.dataset.key]=e.target.checked;save(e.target.dataset.key);e.target.closest('.event')?.classList.toggle('complete',e.target.checked);if(current){const d=TRIP.days[current-1],done=d.timeline.filter(t=>state[t.id]).length;$('#count').textContent=`已完成 ${done} / ${d.timeline.length}`;$('#progress').value=done;}}if(e.target.dataset.flight&&e.target.value){state[flightKey(TRIP.days[Number(e.target.dataset.flight)-1])]=e.target.value;save(flightKey(TRIP.days[Number(e.target.dataset.flight)-1]));render();}});
window.addEventListener('hashchange',()=>render(true));render();


window.applyCloudState=next=>{state=next;render();};
